CarDealershipWeekFive/CarDealership/Models/Car.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace CarDealership.Models
{
    public class Car
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Make is required")]
        public string Make { get; set; }

        [Required(ErrorMessage = "Model is required")]
        public string Model { get; set; }

        [Required(ErrorMessage = "Year is required")]
        public string Year { get; set; }

        [Required(ErrorMessage = "You must include a picture")]
        public string ImageUrl { get; set; }

        public string Title { get; set; }

        [Required(ErrorMessage = "Description is required")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Price is required")]
        public decimal? Price { get; set; }
    }
    
}

CarDealershipWeekFive/CarDealership/Models/ContactForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;

namespace CarDealership.Models
{
    public class ContactForm
    {
        // Your task is to:
        //
        // Make all fields required
        // Ensure the Email field contains an '@' symbol
        // Ensure PhoneNumber is in the format: 1-XXX-XXX-XXXX
        // If the Income is less than 10000 and the PurchaseTimeFrameInMonts is greater than 12,
        // generate a model level area that says 'We don't want your business!'

        [Required(ErrorMessage = "Name is required")]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "Purchasing Time Frame")]
        public int PurchaseTimeFrameInMonths { get; set; }

        [Display(Name = "Phone Number")]
        [ProperPhoneNumber(ErrorMessage = "Format = XXX-XXX-XXXX")]
        public string PhoneNumber { get; set; }

        [Required(ErrorMessage = "Please enter a valid email address")]
        [Display(Name = "Email")]
        [ProperEmail(ErrorMessage = "Please enter a valid email address")]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Income")]
        [MinimumIncome(ErrorMessage = "Minimum is $20,000")]
        public decimal? Income { get; set; }

    }

    public class ProperEmail : ValidationAttribute
    {
        public override bool IsValid(object value)
        {
            if (value == null)
            {
                return false;
            }
            string email = value.ToString();
            if (email == null)
            {
                return false;
            }
            if (email.Contains('@'))
            {
                return base.IsValid(value);
            }
            return false;
            
        }
    }

    public class MinimumIncome : ValidationAttribute
    {
        public override bool IsValid(object value)
        {
            if (value == null)
            {
                return false;
            }
            string income = value.ToString();
            decimal incomeSansCommas = decimal.Parse(income.Replace(",", ""));
            if (incomeSansCommas >= 20000)
            {
                return base.IsValid(value);
            }
            return false;
            
        }
    }

    public class ProperPhoneNumber : ValidationAttribute
    {
        public override bool IsValid(object value)
        {
            if (value == null)
            {
                return false;
            }
            string number = value.ToString();
            if (Regex.IsMatch(number, @"\d{ 3}\-\d{ 3}-\d{ 4}"))
            {
                return base.IsValid(value);
            }

            return false;
        }
    }
}

CarDealershipWeekFive/CarDealership/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CarDealership.Models
{
    public class User
    {
        public int UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string UserMessage { get; set; }
    }
}

CarDealershipWeekFive/CarDealership/Controllers/CarController.cs
using CarDealership.Models;
using CarDealership.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarDealership.Controllers
{
    public class CarController : Controller
    {
        ICarRepository _repo = new MockCarRepository();

        // GET: Car
        public ActionResult Index()
        {
            var cars = _repo.GetAllCars();
            return View(cars);
        }

        public ActionResult Details(int id)
        {
            var car = _repo.GetCarById(id);
            return View(car);
        }

        public ActionResult Details2(string Year, string Make, string Model)
        {
            var car = _repo.GetCarDetails(Year, Make, Model);
            return View("Details", car);
        }

        public ActionResult Add()
        {
            return View(new Car());
        }

        [HttpPost]
        public ActionResult Add(Car newCar)
        {
            _repo.AddCar(newCar);
            return RedirectToAction("Index");
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LoginUser(string username, string password)
        {
            var user = _repo.LoginUser(username, password);
            ViewBag.User = user;
            if (user == null)
            {
                return View("Login");
            }
            else { 
                var cars = _repo.GetAllCars();
                return View("Index", cars);
            }
        }
    }
}

CarDealershipWeekFive/CarDealership/Controllers/HomeController.cs
using CarDealership.Models;
using CarDealership.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarDealership.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contact us using the form below!";

            return View();
        }

        [HttpPost]
        public ActionResult Sales(ContactForm contactForm)
        {
            ViewBag.Message = "Contact us using the form below!";

            if (ModelState.IsValid)
            {
                // yay, send a sales guy an email
                return RedirectToAction("Thanks");
            }
            else
            {
                return View("Contact");
            }
        }

        public ActionResult Thanks()
        {
            return View();
        }
    }
}

CarDealershipWeekFive/CarDealership/Views/Car/Add.cshtml
@model CarDealership.Models.Car
@using CarDealership.Repositories

@{
    ViewBag.Title = "Add";
}

<script>
    $(function () {
        $('#datething').datepicker();
        $('#accord').accordion();
    });
</script>

<h2>Add a Car</h2>
<div class="row">
    @using (Html.BeginForm("Add", "Car"))
    {
        <div>@Html.ValidationSummary(true)</div>
        <div class="col-md-2">
            <div class="form-group">
                <label>Make</label><br />
                    @Html.TextBoxFor(x => x.Make, new { placeholder = "Who makes this car?" })
                    @Html.ValidationMessageFor(x => x.Make)
            </div>
            <div class="form-group">
                <label>Model</label><br />
                    @Html.TextBoxFor(x => x.Model, new { placeholder = "Model name?" })
                    @Html.ValidationMessageFor(x => x.Model)
            </div>
            <div class="form-group">
                <label>Year</label><br />
                    @Html.TextBoxFor(x => x.Year, new { placeholder = "Year?" })
                    @Html.ValidationMessageFor(x => x.Year)
            </div>
            <div class="form-group">
                <label>Image Url</label><br />
                    @Html.TextBoxFor(x => x.ImageUrl, new { placeholder = "Place image here" })
                    @Html.ValidationMessageFor(x => x.ImageUrl)
            </div>
            <div class="form-group">
                <label>Make</label><br />
                    @Html.TextBoxFor(x => x.Title, new { placeholder = "Model name?" })
            </div>
            <div class="form-group">
                <label>Description</label><br />
                    @Html.TextAreaFor(x => x.Description, new { placeholder = "Please describe the vehicle" })
                    @Html.ValidationMessageFor(x => x.Description)
            </div>
            <div class="form-group">
                <label>Price</label><br />
                    @Html.TextBoxFor(x => x.Price, new { placeholder = "Price?" })
                    @Html.ValidationMessageFor(x => x.Price)
            </div>
        </div>
        <button class="btn btn-primary">Submit</button>
    }
</div>

CarDealershipWeekFive/CarDealership/Views/Car/Details.cshtml
@model CarDealership.Models.Car
@{
    ViewBag.Title = "Details";
}

<body>
    <h3>@Html.DisplayFor(m => m.Title)</h3>
    <div class="col-md-10">
        <div id="spacing"><img src="@Html.DisplayFor(m => m.ImageUrl)" /></div>
        <div>
            <p>Make: @Html.DisplayFor(m => m.Make)</p>
            <p>Model: @Html.DisplayFor(m => m.Model)</p>
            <p>Year: @Html.DisplayFor(m => m.Year)</p>
            <p>Price: @Html.DisplayFor(m => m.Price)</p>
            <p>Description:
                @Html.DisplayFor(m => m.Description)</p>
        </div>
    </div>
</body>

CarDealershipWeekFive/CarDealership/Views/Car/Index.cshtml
@model IEnumerable<CarDealership.Models.Car>

@{
    ViewBag.Title = "Index";
}

<h2>Check out these fine, high-quality cars for sale! CLICK FOR DETAILS!</h2>
@if (ViewBag.User != null){
    <h3>@ViewBag.User.UserMessage</h3>
}
<div class="container">

    @for (int i = 0; i < Model.Count(); i = i+3 )
        {
           var ca = Model.ElementAt(i);
            <div class="row">
                <div class="col-md-4">
                    <a href="@Url.Action("Details2", new { year = ca.Year, make = ca.Make, model = ca.Model})">
                        <img src="@ca.ImageUrl" alt="This is a car for sale" class="car-image" />
                    </a>
                </div>
                @if ((i + 1) < Model.Count()) {
                    ca = Model.ElementAt(i+1);
                    <div class="col-md-4">
                        <a href="@Url.Action("Details2", new { year = ca.Year, make = ca.Make, model = ca.Model})">
                            <img src="@ca.ImageUrl" alt="This is a car for sale" class="car-image" />
                        </a>
                    </div>
                }
                @if ((i + 2) < Model.Count()) { 
                    ca = Model.ElementAt(i+2);
                    <div class="col-md-4">
                        <a href="@Url.Action("Details2", new { year = ca.Year, make = ca.Make, model = ca.Model})">
                            <img src="@ca.ImageUrl" alt="This is a car for sale" class="car-image" />
                        </a>
                    </div>
                }
            </div>
            <div>&nbsp;
            </div>
        }
</div>

<div>
    <div class="row"><a href="@Url.Action("Add")">Add a car here!</a></div>
</div>

CarDealershipWeekFive/CarDealership/Views/Car/Login.cshtml

@{
    ViewBag.Title = "Login";
}

<script>
    $(function () {
        $('#theForm').submit(function () {
            if ($('#username').val().indexOf("'") > -1) {
                return false;
            }
            return true;
        });
    });
</script>

<h2>Login</h2>

@using (Html.BeginForm("LoginUser", "Car", FormMethod.Post, new { id = "theForm" }))
{
    <div>Username: <input type="text" name="username" id="username" /></div>
    <div>Password: <input type="password" name="password" id="password" /></div>
    <div><input type="submit" value="Login"/></div>
}

CarDealershipWeekFive/CarDealership/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h1 style="font-size:144px;">WE'RE AMAZING</h1>

CarDealershipWeekFive/CarDealership/Views/Home/Contact.cshtml
@model CarDealership.Models.ContactForm

@{
    ViewBag.Title = "Contact";
    var items = new List<SelectListItem>(){
      new SelectListItem() {
          Text = "6 months",
          Value = "6"
      },
            new SelectListItem() {
          Text = "12 months",
          Value = "12"
      },
            new SelectListItem() {
          Text = "24 months",
          Value = "24"
      },
            new SelectListItem() {
          Text = "36 months",
          Value = "36"
      }
    };
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

@using (Html.BeginForm("Sales", "Home", FormMethod.Post))
{
    <div>
        @Html.ValidationSummary(true)
    </div>
    <div>
        <div class="form-group">
            <label>Name</label><br />
            @Html.TextBoxFor(m => m.Name)
            @Html.ValidationMessageFor(m => m.Name)
        </div>
        <div class="form-group">
            <label>Phone Number</label><br/>
            @Html.TextBoxFor(m => m.PhoneNumber)
            @Html.ValidationMessageFor(m => m.PhoneNumber)
        </div>
        <div class="form-group">
            <label>Time frame to purchase a new car</label><br />
            @Html.DropDownListFor(m => m.PurchaseTimeFrameInMonths, items)
            
        </div>
        <div class="form-group">
            <label>Email</label><br />
            @Html.TextBoxFor(m => m.Email)
            @Html.ValidationMessageFor(m => m.Email)
        </div>
        <div class="form-group">
            <label>Income</label><br />
            @Html.TextBoxFor(m => m.Income)<br/>
            @Html.ValidationMessageFor(m => m.Income)<br />
        </div>
        <div>
            <button>Submit</button>
        </div>
    </div>
}

CarDealershipWeekFive/CarDealership/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Welcome to the SWCG Car Dealership!</h1>
    <p>Go ahead and look around!</p>
</div>

CarDealershipWeekFive/CarDealership/Views/Home/Thanks.cshtml

@{
    ViewBag.Title = "Thanks";
}

<h2>Thanks!!!!!!!!!!!!!!!!!!!!!!!!!!!!!</h2>


CarDealershipWeekFive/CarDealership/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SWCG Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SWCG", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Cars", "Index", "Car")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SWCG</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>